// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToHistory(arg1, arg2) {
  return window['go']['main']['App']['AddToHistory'](arg1, arg2);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CopyContentToClipboard(arg1) {
  return window['go']['main']['App']['CopyContentToClipboard'](arg1);
}

export function DecodeQRFromBase64(arg1) {
  return window['go']['main']['App']['DecodeQRFromBase64'](arg1);
}

export function DecodeQRFromFile(arg1) {
  return window['go']['main']['App']['DecodeQRFromFile'](arg1);
}

export function DeleteHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteHistoryEntry'](arg1);
}

export function GenerateBatch(arg1, arg2) {
  return window['go']['main']['App']['GenerateBatch'](arg1, arg2);
}

export function GenerateQR(arg1) {
  return window['go']['main']['App']['GenerateQR'](arg1);
}

export function GenerateQRWithLogo(arg1, arg2) {
  return window['go']['main']['App']['GenerateQRWithLogo'](arg1, arg2);
}

export function GetHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetHistory'](arg1, arg2, arg3);
}

export function ParseCSV(arg1) {
  return window['go']['main']['App']['ParseCSV'](arg1);
}

export function PickAndDecodeImage() {
  return window['go']['main']['App']['PickAndDecodeImage']();
}

export function PickCSVFile() {
  return window['go']['main']['App']['PickCSVFile']();
}

export function PickLogoImage() {
  return window['go']['main']['App']['PickLogoImage']();
}

export function SaveQRPNG(arg1) {
  return window['go']['main']['App']['SaveQRPNG'](arg1);
}

export function SaveQRSVG(arg1) {
  return window['go']['main']['App']['SaveQRSVG'](arg1);
}

export function SaveSheetPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSheetPDF'](arg1, arg2, arg3);
}

export function SaveSheetPNG(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSheetPNG'](arg1, arg2, arg3);
}
