// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyContentToClipboard(arg1) {
  return window['go']['main']['App']['CopyContentToClipboard'](arg1);
}

export function GenerateQR(arg1) {
  return window['go']['main']['App']['GenerateQR'](arg1);
}

export function SaveQRPNG(arg1) {
  return window['go']['main']['App']['SaveQRPNG'](arg1);
}

export function SaveSheetPNG(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSheetPNG'](arg1, arg2, arg3);
}
