// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddToHistory(arg1:main.QRRequest,arg2:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function CopyContentToClipboard(arg1:string):Promise<void>;

export function DecodeQRFromBase64(arg1:string):Promise<string>;

export function DecodeQRFromFile(arg1:string):Promise<string>;

export function DeleteHistoryEntry(arg1:number):Promise<void>;

export function GenerateBatch(arg1:main.QRRequest,arg2:string):Promise<Array<main.BatchResult>>;

export function GenerateQR(arg1:main.QRRequest):Promise<main.QRResponse>;

export function GenerateQRWithLogo(arg1:main.QRRequest,arg2:string):Promise<main.QRResponse>;

export function GetHistory(arg1:string,arg2:number,arg3:number):Promise<Array<main.HistoryEntry>>;

export function ParseCSV(arg1:string):Promise<main.CSVParseResult>;

export function PickAndDecodeImage():Promise<string>;

export function PickCSVFile():Promise<string>;

export function PickLogoImage():Promise<string>;

export function SaveQRPNG(arg1:string):Promise<string>;

export function SaveQRSVG(arg1:main.QRRequest):Promise<string>;

export function SaveSheetPDF(arg1:main.QRRequest,arg2:number,arg3:number):Promise<string>;

export function SaveSheetPNG(arg1:main.QRRequest,arg2:number,arg3:number):Promise<string>;
