// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyContentToClipboard(arg1:string):Promise<void>;

export function GenerateQR(arg1:main.QRRequest):Promise<main.QRResponse>;

export function SaveQRPNG(arg1:string):Promise<string>;

export function SaveSheetPNG(arg1:main.QRRequest,arg2:number,arg3:number):Promise<string>;
